#!/usr/bin/env node
/* Build assets/course-index.js — a small, plain-text digest of the course
   used by the Today page, Daily review and Listen & repeat, so those pages
   don't have to load the full course files.

   Run from the repository root after editing course content:
     node tools/build-index.js
*/
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
global.window = {};
for (const f of ["1", "2", "3", "4", "t2", "5"]) require(path.join(ROOT, "assets", "course-" + f + ".js"));
require(path.join(ROOT, "assets", "course-en.js"));
const M = window.COURSE.modules, EN = window.COURSE_EN;

const strip = s => String(s || "").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();

/* mistakes: [wrong, right, why, module, English for right] */
const out = { modules: [], vocab: [], mistakes: [], lines: [] };
M.forEach((m, i) => {
  /* n / ls / focus feed the brain map on Today (lesson count, lesson titles, short TCF kit) */
  out.modules.push({ id: m.id, num: i, level: m.level, title: m.title, n: m.lessons.length, ls: m.lessons.map(L => strip(L.title)), focus: !!m.focus, quiz: !!(m.quiz && m.quiz.length) });
  (m.vocab || []).forEach(v => out.vocab.push([strip(v[0]), strip(v[1]), m.id]));
  /* only the French mistakes (the exam modules also list English strategy tips);
     a French "right" version is one that has an English translation */
  (m.mistakes || []).forEach(x => {
    const right = strip(x[1]), en = EN.scoped[m.id + "|" + right] || EN.map[right];
    if (en && !/^✗/.test(en)) out.mistakes.push([strip(x[0]), right, strip(x[2]), m.id, en]);
  });
  if (m.speak) m.speak.lines.forEach(l => out.lines.push([strip(l[0]), strip(l[1]), m.id]));
});
const js = "/* Generated by tools/build-index.js from assets/course-*.js — do not edit by hand. */\n" +
  "window.COURSE_INDEX = " + JSON.stringify(out) + ";\n";
fs.writeFileSync(path.join(ROOT, "assets", "course-index.js"), js);
console.log("modules", out.modules.length, "vocab", out.vocab.length, "mistakes", out.mistakes.length, "lines", out.lines.length, "bytes", js.length);
